### ISSUE TITLE
Menú Inicio sin completar

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-game_of_codes#1]
Hay un fichero de código que contiene un esqueleto de menú, pero no tiene información útil. Evidentemente se trata aún de una versión preliminar, pero debéis incluir información, al menos en forma de comentarios, que me permita evaluar el progreso.

**Comment by sfonseca2019** [comment]
Buenas tardes profesor, ya se ha realizado una actualización breve del menú donde se comenta algunos juegos añadidos y otros que se añadirán en un futuro.
