### ISSUE TITLE
Código no portable

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-game_of_codes#2]
En vuestro código empleáis llamadas a comandos específicos de Windows. Esto hace que vuestro código no sea portable, es decir, no se puede compilar o ejecutar en otros sistemas operativos.
Por ejemplo, `system(cls)`: https://www.daniweb.com/programming/software-development/threads/95284/clearing-screen-in-the-console
En particular, las pruebas de código tras la entrega final se harán con sistema automático que trabaja en Linux, debéis evitar estas llamadas.

**Comment by hfranco47** [comment]
Buenas Oscar. Ya hemos eliminado los comandos "system" Para tenerlo en cuenta en próximos códigos, ¿qué otros comandos específicos de windows hay? Gracias.

**Comment by oscarperpinan** [comment]
> Ya hemos eliminado los comandos "system" 

Aún quedan algunos:

https://github.com/aigora/twE105_1920-game_of_codes/blob/33e911c7f3d55061cd9da0745f63a38734dcfd1b/GameOfCodes.c#L20

> Para tenerlo en cuenta en próximos códigos, ¿qué otros comandos específicos de windows hay? 

Debéis evitar el uso de librerías específicas de Windows. Por ejemplo: https://en.wikipedia.org/wiki/Conio.h
