### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-game_of_codes#3]
[Don't Repeat Yourself](https://www.oreilly.com/library/view/97-things-every/9780596809515/ch30.html)

Por ejemplo, la siguiente función...
https://github.com/aigora/twE105_1920-game_of_codes/blob/ca0e624b6f4e2b600b0712254422384f79e114bf/GameOfCodes.c#L167
...es un conjunto de copia-pega del mismo código con variaciones menores. 
La función siguiente (jugador2) es básicamente la misma función con una adaptación menor para otro jugador. 
Debéis reescribir estas funciones de manera abstracta y general, evitando repetir código. Esto mejorará el mantenimiento de vuestro código y os facilitará la implementación de cambios y mejoras.

**Comment by hfranco47** [comment]
@oscarperpinan Creo que he arreglado la repetición de los jugadores generalizando más el código.

**Comment by oscarperpinan** [comment]
Mucho mejor, pero aún podéis unir las dos funciones jugador1 y jugador2 en una única función.

**Comment by hfranco47** [comment]
@oscarperpinan Buenas Óscar, ya he unido las funciones jugador1 y jugador2. Ahora me pondré a mejorar la función ganador.
