### ISSUE TITLE
Ficheros y estructuras

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_1920-game_of_codes#4]
Recordad que el programa debe utilizar ficheros y vectores de estructuras. En particular, para el uso de ficheros podéis almacenar tableros de los diferentes juegos, guardar el registro de los usuarios, etc.

**Comment by hfranco47** [comment]
@oscarperpinan En el código de presentación guardamos el registro en ficheros y utilizamos un vector de estructuras, y en el nuevo juego Preguntados cogemos las preguntas de ficheros.

**Comment by oscarperpinan** [comment]
No lo he visto. ¿Puedes enlazarme las líneas de código a las que te refieres?

**Comment by hfranco47** [comment]
@oscarperpinan En Game_of_codes.c 
![Captura](https://user-images.githubusercontent.com/47787868/80685972-455c7180-8ac8-11ea-977c-edff38c5afc6.PNG)

**Comment by oscarperpinan** [comment]
Ok. Para la siguiente, para enlazar código no hace falta capturar una imagen. Mirad [aquí](https://help.github.com/es/github/managing-your-work-on-github/creating-a-permanent-link-to-a-code-snippet) cómo se hace.

 La estructura sí la había visto. La escritura del fichero no la había visto. Pero, ¿qué hacéis con la información que grabáis en el fichero? ¿Dónde está el fscanf correspondiente?. Se trata de hacer gestión de información en ficheros.

**Comment by hfranco47** [comment]
@oscarperpinan De momento solo escribe en el fichero Usuario.txt los datos que se preguntan. De momento no se hace nada con la información grabada.

**Comment by oscarperpinan** [comment]
Veo que estáis usando ficheros para las preguntas. Me llama la atención que uséis un fichero para cada pregunta. ¿Por qué no todas las preguntas/respuestas en un único fichero? Así es más fácil de mantener, y os permite alterar el orden de las preguntas fácilmente.

**Comment by hfranco47** [comment]
@oscarperpinan Lo he intentado, pero si metemos todas las preguntas en un único fichero no sé como leer las preguntas de una en una. Se me había ocurrido meter las preguntas en una cadena y con un bucle for enseñar de tal carácter a otro.

**Comment by oscarperpinan** [comment]
Puedes usar la especificación de formato [%\n] para leer todo lo que esté en una línea.

**Comment by oscarperpinan** [comment]
Puedes usar el identificador de formato %[^\n] para leer una línea completa.

**Comment by hfranco47** [comment]
@oscarperpinan Pero si metemos todas preguntas en un mismo fichero, ¿cómo pasamos de una en una cada pregunta?

**Comment by oscarperpinan** [comment]
Leed el fichero completo, y guardad el contenido en un [vector de cadenas de caracteres](https://stackoverflow.com/questions/1088622/how-do-i-create-an-array-of-strings-in-c). Cada elemento del vector es una pregunta. Recorred el vector de forma secuencial o aleatoria, y estaréis recorriendo las preguntas.

**Comment by hfranco47** [comment]
@oscarperpinan Y se podría almacenar cada pregunta en una cadena diferente? (leyendolas de un mismo fichero)
Algo así:
![Captura1](https://user-images.githubusercontent.com/47787868/81508278-76784580-9303-11ea-9375-79827bea6cac.PNG)

**Comment by oscarperpinan** [comment]
Sí, pero es justo lo que intentamos evitar. Esta solución no es escalable: imagina que tuvieras 100 preguntas. Necesitarías 100 variables diferentes. Con un vector de cadenas puedes tener las preguntas que quieras sin modificar el código.

**Comment by hfranco47** [comment]
@oscarperpinan Si, ya lo veo, gracias.
¿Sería esta una buena manera de emplear el vector de cadenas?
El vector sería: preguntas [Número de preguntas] [Número de caracteres de cada pregunta]
![Captura1](https://user-images.githubusercontent.com/47787868/81548557-c267d080-937d-11ea-87b9-82fd12ef24f5.PNG)

**Comment by oscarperpinan** [comment]
Antes de responder a tu pregunta: no insertes capturas (imágenes) de código. El código es texto plano, y se puede copiar directamente en el cuadro de texto. Para que quede "bonito" puedes hacer lo que explican aquí: https://help.github.com/es/github/writing-on-github/creating-and-highlighting-code-blocks

Sobre tu pregunta: sí, así estaría bien pero no lo definas como una constante.

**Comment by hfranco47** [comment]
@oscarperpinan De acuerdo, muchas gracias.
